apiVersion: v1
kind: Service
metadata:
  name: llmconfig-service
spec:
  selector:
    app: llmconfig-app
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30002
  type: ClusterIP

